trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
    displayName: 'Yarn Install'
    inputs:
        projectDirectory: '$(System.DefaultWorkingDirectory)/Cypress'
        arguments: install